server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 50000
        response-timeout: 50000
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://frontimage:3000'
              - 'http://localhost:3000'
              - 'http://34.64.88.166:3000'
              - 'https://tubeplus.online'
            allow-credentials: false
            #            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - PATCH
              - OPTIONS

      routes:
        - id: user-service # server name
          #          uri: http://localhost:9000 # server ip
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/** # root path after gateway path
        - id: etc-service
          #          uri: http://localhost:9001
          uri: lb://ETC-SERVICE
          predicates:
            - Path=/api/v1/etc/**
        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/api/v1/communities/**
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/api/v1/boards/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaimage:8761/eureka/ # all managed by eureka
